# Generated by Django 5.2.14 on 2026-06-01 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=4.5)),
                ('reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('duration_label', models.CharField(max_length=100)),
                ('class_type', models.CharField(max_length=100)),
                ('class_label', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField(default=44)),
                ('available_seats', models.IntegerField(default=44)),
                ('price', models.IntegerField(default=0)),
                ('amenities', models.TextField(default='')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_email', models.CharField(max_length=255)),
                ('passenger_phone', models.CharField(max_length=50)),
                ('passenger_document', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('EMBARCADO', 'Embarcado'), ('UTILIZADO', 'Utilizado')], default='CONFIRMADO', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('validation_date', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_token', models.CharField(max_length=255, unique=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('validated_by', models.CharField(max_length=255)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='api.reservation')),
            ],
        ),
    ]
