# Generated by Django 5.2.14 on 2026-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_ano_fundacao_company_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
