# Generated by Django 5.2.14 on 2026-06-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'CLIENTE'), ('ADMIN', 'ADMIN'), ('OPERADOR', 'OPERADOR'), ('FISCAL', 'FISCAL')], default='CLIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PopularRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(blank=True, null=True, upload_to='popular_routes/')),
                ('duracao', models.CharField(default='8h 30min', max_length=50)),
                ('preco_desde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequencia', models.CharField(default='Diário', max_length=50)),
                ('trending', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_routes_to', to='api.location')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_routes_from', to='api.location')),
            ],
            options={
                'db_table': 'popular_routes',
            },
        ),
    ]
