# Generated by Django 5.2.14 on 2026-06-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_logo_alter_userprofile_role_popularroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='colunas_direita',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bus',
            name='colunas_esquerda',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bus',
            name='linhas',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='bus',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
