# Generated by Django 5.2.14 on 2026-06-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bus_seat_layout_fiscais'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
