# Generated by Django 5.2.14 on 2026-06-19 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_location_company_route_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_reschedule', models.BooleanField(default=True)),
                ('reschedule_window_hours', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelation_policy', to='api.company')),
            ],
            options={
                'db_table': 'cancelation_policies',
            },
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('carrier_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('administrative_retention', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('financial_destination', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_logs', to='api.reservation')),
            ],
            options={
                'db_table': 'financial_audit_logs',
            },
        ),
        migrations.CreateModel(
            name='CancelationPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hours_before_departure', models.IntegerField()),
                ('retention_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('flat_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.cancelationpolicy')),
            ],
            options={
                'db_table': 'cancelation_policy_rules',
                'unique_together': {('policy', 'min_hours_before_departure')},
            },
        ),
    ]
