# Generated by Django 5.2.14 on 2026-06-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('CONFIRMADA', 'CONFIRMADA'), ('CANCELADA', 'CANCELADA'), ('EMBARCADO', 'EMBARCADO'), ('PENDENTE_CANCELAMENTO', 'PENDENTE_CANCELAMENTO')], default='CONFIRMADA', max_length=50),
        ),
    ]
