# Generated by Django 5.2.14 on 2026-06-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dados_bancarios', models.TextField(help_text='IBAN, Banco, Titular, etc.')),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('APROVADO', 'APROVADO'), ('REJEITADO', 'REJEITADO')], default='PENDENTE', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='comprovativos_saques/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='api.company')),
            ],
            options={
                'db_table': 'withdrawals',
            },
        ),
    ]
