name: Deploy NZILA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            sudo sh -c 'echo "client_max_body_size 10M;" > /etc/nginx/conf.d/client_max_body_size.conf'
            sudo systemctl reload nginx
            cd /var/www/nzila
            git pull origin main
            ./deploy.sh
